export const authConstants = {
    STUDENT_LOGIN_REQUEST: "STUDENT_LOGIN_REQUEST",
    STUDENT_LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
    STUDENT_LOGIN_FAILURE: "STUDENT_LOGIN_FAILURE",

    TEACHER_LOGIN_REQUEST: "TEACHER_LOGIN_REQUEST",
    TEACHER_LOGIN_SUCCESS: "TEACHER_LOGIN_SUCCESS",
    TEACHER_LOGIN_FAILURE: "TEACHER_LOGIN_FAILURE",

    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    STUDENT_REGISTER_REQUEST: "STUDENT_REGISTER_REQUEST",
    STUDENT_REGISTER_SUCCESS: "STUDENT_REGISTER_SUCCESS",
    STUDENT_REGISTER_FAILURE: "STUDENT_REGISTER_FAILURE",

    TEACHER_REGISTER_REQUEST: "TEACHER_REGISTER_REQUEST",
    TEACHER_REGISTER_SUCCESS: "TEACHER_REGISTER_SUCCESS",
    TEACHER_REGISTER_FAILURE: "TEACHER_REGISTER_FAILURE",

    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    STUDENT_LOGOUT_REQUEST: "STUDENT_LOGOUT_REQUEST",
    STUDENT_LOGOUT_SUCCESS: "STUDENT_LOGOUT_SUCCESS",
    STUDENT_LOGOUT_FAILURE: "STUDENT_LOGOUT_FAILURE",

    TEACHER_LOGOUT_REQUEST: "TEACHER_LOGOUT_REQUEST",
    TEACHER_LOGOUT_SUCCESS: "TEACHER_LOGOUT_SUCCESS",
    TEACHER_LOGOUT_FAILURE: "TEACHER_LOGOUT_FAILURE",
}

export const fetchConstants = {
    STUDENT_FETCH_REQUEST: "STUDENT_FETCH_REQUEST",
    STUDENT_FETCH_SUCCESS: "STUDENT_FETCH_SUCCESS",
    STUDENT_FETCH_FAILURE: "STUDENT_FETCH_FAILURE",

    ATTENDENCE_FETCH_REQUEST: "ATTENDENCE_FETCH_REQUEST",
    ATTENDENCE_FETCH_SUCCESS: "ATTENDENCE_FETCH_SUCCESS",
    ATTENDENCE_FETCH_FAILURE: "ATTENDENCE_FETCH_FAILURE",
}

export const addConstants = {
    ATTENDENCE_ADDING_REQUEST: "ATTENDENCE_ADDING_REQUEST",
    ATTENDENCE_ADDING_SUCCESS: "ATTENDENCE_ADDING_SUCCESS",
    ATTENDENCE_ADDING_FAILURE: "ATTENDENCE_ADDING_FAILURE",
}